# Generated by Django 5.2.6 on 2025-09-19 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='sobre',
            field=models.TextField(blank=True, null=True),
        ),
    ]
